spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888,optional:vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: dev/auth-service