ALTER TABLE users
    ADD COLUMN created_by VARCHAR(255),
ADD COLUMN created_date TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN last_modified_by VARCHAR(255),
ADD COLUMN last_modified_date TIMESTAMP WITHOUT TIME ZONE;