server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sia_auth_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
jwt:
  secret: "6XAewBPP/DO4xY1Gw7iAZXJvfmDP1wkv5o26maw5N2s="
  expiration:
    access-token: 600000   # 10 minutes
    refresh-token: 604800000 # 7 days